### ISSUE TITLE
400 error on deploying contract on localterra: "Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interfaceversion*"

### ISSUE THREAD

**Issue by taitruong** [terran6/nft-on-terra#1]
I'm a noob and newbie, trying to explain from what I understood :). Problem seems to relate using wron CosmWasm version resp. needs to be updated for working on Terra 2.
Tried to update dependencies Cargo.toml, but then I get an 404 error when deploying. Find details describe on new Terra (not classic) discord:
- discord link: https://terra.sc/discord
- message link: https://discord.com/channels/983359798059892766/983726119507345508/989903497694703706

**Comment by terran6** [comment]
Hey @taitruong!  I just got around to updating this tutorial.  Please give it another try if you are interested and thanks for alerting me of the issue.
